spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tobelist
    username: ttube
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  secret: Z2RzYy1za2h1LWJhY2tlbmQtand0LXN0dWR5LWRlY2VtYmVyLTI4dGgtaml5dW5sZWU=
  token-validity-in-milliseconds: 86400000
